// Auto-generated by _convert/organize.mjs — do not edit by hand.
// Run organize.mjs again to regenerate.

export type ServiceImage = { src: string; alt: string; title: string };

export const SERVICE_IMAGES: Record<string, ServiceImage[]> = {
  "decks-porches": [
    {
      "src": "/images/services/decks-porches/decks-porches-01.jpg",
      "alt": "Custom cedar deck with railings on a Somerset KY home, built by Rust & Sawdust.",
      "title": "Custom cedar deck · Somerset, KY"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-02.jpg",
      "alt": "Open pressure-treated deck and rail overlooking the back yard of a Kentucky home.",
      "title": "Open deck build · Pulaski County, KY"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-03.jpg",
      "alt": "Refinished deck with new pressure-treated boards on a Lake Cumberland area home.",
      "title": "Deck refinish · Lake Cumberland, KY"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-04.jpg",
      "alt": "Cedar deck board detail showing tight joinery and finish carpentry.",
      "title": "Deck detail · cedar finish"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-05.jpg",
      "alt": "Finished deck and railing built for outdoor living in Somerset, Kentucky.",
      "title": "Finished deck and railing · Somerset, KY"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-06.jpg",
      "alt": "Backyard deck and outdoor living space added to a Pulaski County KY home.",
      "title": "Backyard deck · Pulaski County, KY"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-07.jpg",
      "alt": "Custom front porch and entry on a renovated Kentucky home by Rust & Sawdust.",
      "title": "Front porch entry · Kentucky"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-08.jpg",
      "alt": "Lake Cumberland view from a custom-built deck on a Somerset KY lake house.",
      "title": "Lake Cumberland deck view"
    },
    {
      "src": "/images/services/decks-porches/decks-porches-09.jpg",
      "alt": "Lakefront deck view at sunset from a Somerset KY home built for lake life.",
      "title": "Lakefront deck · Somerset, KY"
    }
  ],
  "screened-rooms-pergolas": [
    {
      "src": "/images/services/screened-rooms-pergolas/screened-rooms-pergolas-01.jpg",
      "alt": "Covered patio outdoor living room with seating on a Somerset KY home.",
      "title": "Covered patio room · Somerset, KY"
    },
    {
      "src": "/images/services/screened-rooms-pergolas/screened-rooms-pergolas-02.jpg",
      "alt": "Cedar porch roof framing over a stone entry on a custom home in Pulaski County, KY.",
      "title": "Cedar porch roof · Pulaski County, KY"
    },
    {
      "src": "/images/services/screened-rooms-pergolas/screened-rooms-pergolas-03.jpg",
      "alt": "Covered porch with columns built for Kentucky weather and outdoor entertaining.",
      "title": "Covered porch with columns"
    },
    {
      "src": "/images/services/screened-rooms-pergolas/screened-rooms-pergolas-04.jpg",
      "alt": "Cedar pergola-style kayak storage shelter at a Lake Cumberland lake house.",
      "title": "Pergola kayak shelter · Lake Cumberland"
    },
    {
      "src": "/images/services/screened-rooms-pergolas/screened-rooms-pergolas-05.jpg",
      "alt": "Outdoor view of Lake Cumberland from a finished porch and deck space.",
      "title": "Outdoor living view · Lake Cumberland"
    },
    {
      "src": "/images/services/screened-rooms-pergolas/screened-rooms-pergolas-06.jpg",
      "alt": "Lakefront outdoor living view from a Somerset KY home overlooking the water.",
      "title": "Lakefront outdoor space · Somerset, KY"
    }
  ],
  "buildings-barns-sheds": [
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-01.jpg",
      "alt": "Custom dark-blue metal garage with double white roll-up doors in Somerset, KY.",
      "title": "Custom metal garage · Somerset, KY"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-02.jpg",
      "alt": "Post-frame pole barn with metal roof built in Pulaski County, Kentucky.",
      "title": "Pole barn · Pulaski County, KY"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-03.jpg",
      "alt": "Brown metal pole barn built as a workshop and storage building in Somerset KY.",
      "title": "Metal pole barn · Somerset, KY"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-04.jpg",
      "alt": "Custom brown garage with a tall roll-up door for RV or boat storage.",
      "title": "Tall-door garage · Kentucky"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-05.jpg",
      "alt": "Large finished post-frame outbuilding matched to the homeowner's existing home.",
      "title": "Finished outbuilding · Lake Cumberland"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-06.jpg",
      "alt": "Post-frame storage building in Pulaski County KY with metal roof and matching trim.",
      "title": "Post-frame storage building · Pulaski County, KY"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-07.jpg",
      "alt": "Rust & Sawdust crew framing a small pole barn in winter weather in Kentucky.",
      "title": "Pole barn framing · Kentucky"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-08.jpg",
      "alt": "Pole barn interior built with horse stalls and storage in Pulaski County, KY.",
      "title": "Horse barn interior · Pulaski County, KY"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-09.jpg",
      "alt": "Custom workshop interior with full tool storage and pegboard walls.",
      "title": "Custom workshop interior"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-10.jpg",
      "alt": "Finished interior of a large custom garage build in Somerset, Kentucky.",
      "title": "Custom garage interior · Somerset, KY"
    },
    {
      "src": "/images/services/buildings-barns-sheds/buildings-barns-sheds-11.jpg",
      "alt": "Small white outbuilding finished to match the homeowner's existing house style.",
      "title": "Matching outbuilding · Kentucky"
    }
  ],
  "concrete-excavating": [
    {
      "src": "/images/services/concrete-excavating/concrete-excavating-01.jpg",
      "alt": "Newly paved driveway with curb work in Somerset, Kentucky by Rust & Sawdust.",
      "title": "Driveway and curb work · Somerset, KY"
    },
    {
      "src": "/images/services/concrete-excavating/concrete-excavating-02.jpg",
      "alt": "Stained decorative concrete patio finish in a Pulaski County KY back yard.",
      "title": "Stained decorative concrete patio"
    },
    {
      "src": "/images/services/concrete-excavating/concrete-excavating-03.jpg",
      "alt": "Custom stone walkway and entry hardscape on a Kentucky home.",
      "title": "Stone walkway and entry"
    },
    {
      "src": "/images/services/concrete-excavating/concrete-excavating-04.jpg",
      "alt": "Backyard hardscape and stone retaining wall built in Somerset KY.",
      "title": "Stone retaining wall · Somerset, KY"
    },
    {
      "src": "/images/services/concrete-excavating/concrete-excavating-05.jpg",
      "alt": "Backyard concrete patio with privacy fence in Pulaski County, Kentucky.",
      "title": "Concrete patio · Pulaski County, KY"
    },
    {
      "src": "/images/services/concrete-excavating/concrete-excavating-06.jpg",
      "alt": "Fresh concrete patio pad poured for a new outdoor living space in Somerset KY.",
      "title": "Concrete patio pad pour · Somerset, KY"
    }
  ],
  "custom-woodwork": [
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-01.jpg",
      "alt": "Live-edge walnut shelf detail custom-built for a Somerset KY home.",
      "title": "Live-edge walnut shelf · Somerset, KY"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-02.jpg",
      "alt": "Industrial pipe shelving over hex tile flooring in a custom remodel.",
      "title": "Industrial pipe shelving"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-03.jpg",
      "alt": "Custom closet shelving and built-in storage system in a Pulaski County home.",
      "title": "Custom closet shelving"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-04.jpg",
      "alt": "Built-in white shelving for a laundry room in a Kentucky home.",
      "title": "Built-in white shelving"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-05.jpg",
      "alt": "Custom kitchen build with wood-detail counters and rustic finishes.",
      "title": "Custom kitchen with wood counters"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-06.jpg",
      "alt": "Custom cedar plank kitchen counter built by Rust & Sawdust in Somerset KY.",
      "title": "Cedar plank counter · Somerset, KY"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-07.jpg",
      "alt": "Butcher block kitchen counter installation in a Lake Cumberland area home.",
      "title": "Butcher block counter · Lake Cumberland"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-08.jpg",
      "alt": "Dark live-edge wood kitchen counter custom-built for a Kentucky remodel.",
      "title": "Dark live-edge counter · Kentucky"
    },
    {
      "src": "/images/services/custom-woodwork/custom-woodwork-09.jpg",
      "alt": "Custom wood kitchen counter finish detail showing hand-crafted joinery.",
      "title": "Custom kitchen counter detail"
    }
  ],
  "additions-remodels": [
    {
      "src": "/images/services/additions-remodels/additions-remodels-01.jpg",
      "alt": "Custom two-story home addition exterior with board-and-batten siding in Somerset, KY.",
      "title": "Custom home addition · Somerset, KY"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-02.jpg",
      "alt": "Stone-front custom home addition in the Lake Cumberland region of Kentucky.",
      "title": "Stone-front addition · Lake Cumberland"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-03.jpg",
      "alt": "White kitchen remodel with stainless steel appliances in a Pulaski County KY home.",
      "title": "White kitchen remodel · Pulaski County, KY"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-04.jpg",
      "alt": "Bright yellow kitchen remodel with custom cabinetry and finish work.",
      "title": "Yellow kitchen remodel"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-05.jpg",
      "alt": "Bathroom remodel with marble vanity countertop and custom finishes.",
      "title": "Bathroom remodel · marble vanity"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-06.jpg",
      "alt": "Custom tiled walk-in shower remodel in a Somerset KY home.",
      "title": "Tiled walk-in shower · Somerset, KY"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-07.jpg",
      "alt": "Stone shower bench and pebble floor detail in a Kentucky bathroom remodel.",
      "title": "Stone shower bench detail"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-08.jpg",
      "alt": "Walk-in shower with frameless glass door and stone tile surround.",
      "title": "Walk-in shower with glass door"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-09.jpg",
      "alt": "Commercial bathroom remodel completed in Pulaski County, Kentucky.",
      "title": "Commercial bathroom remodel · Pulaski County, KY"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-10.jpg",
      "alt": "Commercial restroom remodel with stalls in a Somerset KY facility.",
      "title": "Commercial restroom · Somerset, KY"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-11.jpg",
      "alt": "Commercial space remodel and finish carpentry by Rust & Sawdust.",
      "title": "Commercial space remodel"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-12.jpg",
      "alt": "Bathroom remodel with hex tile floor and finished walls in a Kentucky home.",
      "title": "Hex tile bathroom · Kentucky"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-13.jpg",
      "alt": "Floor transition detail between tile and hardwood in a renovated Kentucky home.",
      "title": "Floor transition detail"
    },
    {
      "src": "/images/services/additions-remodels/additions-remodels-14.jpg",
      "alt": "Finished interior of a renovated home in Somerset, KY by Rust & Sawdust.",
      "title": "Renovated interior · Somerset, KY"
    }
  ],
  "windows-trim-painting": [
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-01.jpg",
      "alt": "Custom bay window installation with finish trim in a Somerset KY home.",
      "title": "Bay window install · Somerset, KY"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-02.jpg",
      "alt": "Bay window with custom interior sill and finish carpentry in Pulaski County.",
      "title": "Bay window sill · Pulaski County, KY"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-03.jpg",
      "alt": "Bay window installation paired with new hardwood flooring beneath.",
      "title": "Bay window + floor finish"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-04.jpg",
      "alt": "Bay window with cedar trim and wood floor in a Kentucky home interior.",
      "title": "Cedar-trim bay window"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-05.jpg",
      "alt": "Bay window interior trim and finish carpentry in a Lake Cumberland area home.",
      "title": "Window trim · Lake Cumberland"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-06.jpg",
      "alt": "New luxury vinyl plank flooring installation in a Somerset KY home.",
      "title": "Vinyl plank floor · Somerset, KY"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-07.jpg",
      "alt": "Hallway flooring installation finished by Rust & Sawdust in Pulaski County, KY.",
      "title": "Hallway flooring · Pulaski County, KY"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-08.jpg",
      "alt": "Hardwood floor finish detail in a renovated Somerset KY home.",
      "title": "Hardwood finish detail · Somerset, KY"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-09.jpg",
      "alt": "Vinyl flooring install and trim work in a Lake Cumberland area home.",
      "title": "Vinyl floor + trim · Lake Cumberland"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-10.jpg",
      "alt": "Refinished hardwood floor in a renovated Kentucky home.",
      "title": "Refinished hardwood"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-11.jpg",
      "alt": "Hardwood floor close-up showing tight grain and sanded finish.",
      "title": "Hardwood close-up"
    },
    {
      "src": "/images/services/windows-trim-painting/windows-trim-painting-12.jpg",
      "alt": "Rust & Sawdust on-site painting jobsite in Somerset, KY — any and all paint jobs welcome.",
      "title": "Painting jobsite · Somerset, KY"
    }
  ],
  "golf-greens-specialty": [
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-01.jpg",
      "alt": "Custom backyard putting green build finished in Somerset, KY with flag and cup.",
      "title": "Backyard putting green · Somerset, KY"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-02.jpg",
      "alt": "Custom backyard putting green with flag and cup in a Pulaski County KY yard.",
      "title": "Putting green with flag · Pulaski County"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-03.jpg",
      "alt": "Putting green build in progress with shaping work and turf preparation.",
      "title": "Putting green in progress"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-04.jpg",
      "alt": "Putting green base layout and excavation for a Somerset KY backyard.",
      "title": "Putting green base layout"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-05.jpg",
      "alt": "Indoor golf simulator screen and hitting bay in a custom Kentucky home.",
      "title": "Indoor golf simulator · Kentucky"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-06.jpg",
      "alt": "Custom indoor golf room with Pure Michigan Blvd theme — specialty build by Rust & Sawdust.",
      "title": "Indoor golf room · custom theme"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-07.jpg",
      "alt": "Custom Pure Michigan Blvd street-sign decor for a specialty build.",
      "title": "Custom street-sign decor"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-08.jpg",
      "alt": "Custom indoor climbing wall for a kids' play space in a Somerset KY home.",
      "title": "Indoor climbing wall · Somerset, KY"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-09.jpg",
      "alt": "Climbing wall with built-in storage shelving — custom specialty build.",
      "title": "Climbing wall + shelving"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-10.jpg",
      "alt": "Custom indoor twisting slide for a kids' play area in a Kentucky home.",
      "title": "Indoor twisting slide"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-11.jpg",
      "alt": "Spiral indoor slide for a custom kids' specialty space in Pulaski County KY.",
      "title": "Spiral slide · Pulaski County, KY"
    },
    {
      "src": "/images/services/golf-greens-specialty/golf-greens-specialty-12.jpg",
      "alt": "Custom wooden indoor jungle gym and play space build in Somerset, KY.",
      "title": "Indoor jungle gym · Somerset, KY"
    }
  ]
};

export function getServiceImages(slug: string): ServiceImage[] {
  return SERVICE_IMAGES[slug] ?? [];
}
